### ISSUE TITLE
Need support for decimal values

### ISSUE THREAD

**Issue by ericgrantholland** [muqeet-khan/BlazorComponents#12]
Looks like the chart components only support List<int> types.

**Comment by muqeet-khan** [comment]
https://github.com/muqeet-khan/BlazorComponents/blob/e03ed15a370143512404d4e3f9ca23cf340cfc78/src/BlazorComponents/ChartJS/ChartJsDataset.cs#L13

Yes, this has been a todo item. However, I have been thinking about the approach here. I might make this to accept a double rather than an Int for now.

**Comment by muqeet-khan** [comment]
This has been completed in release 0.4.0.  

Unless no one comes up with a compelling reason to change this we will continue with decimal being the default in the future as well.
